### ISSUE TITLE
Modal Paste Keys

### ISSUE THREAD

**Issue by DouglasPitangui** [tadeuastori/scriptgenerator#1]
Aumentar modal que é exibido ao clicar em **Paste Keys** na tela Translator Key para facilitar a visualização do texto inserido.

![pastekeys](https://user-images.githubusercontent.com/10212978/65255396-2e868300-dad4-11e9-997a-12664ad357e4.png)

**Comment by tadeuastori** [comment]
Em análise!!

**Comment by tadeuastori** [comment]
Obrigado pela sugestão.
Alterado o tamanho do modal. 

![image](https://user-images.githubusercontent.com/12178206/65261365-7dd1b100-dade-11e9-932f-9df4f19eb46e.png)
